#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>

void generateFibonacci(int n, int pipe_fd[]) {
    close(pipe_fd[0]); 

    int a = 0, b = 1;
    int fib;

    for (int i = 0; i < n; ++i) {
        write(pipe_fd[1], &a, sizeof(int));
        fib = a + b;
        a = b;
        b = fib;
    }

    close(pipe_fd[1]); 
    exit(0);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <number_of_fibonacci_numbers>\n", argv[0]);
        exit(1);
    }

    int n = atoi(argv[1]);
    if (n <= 0) {
        fprintf(stderr, "Please enter a positive integer.\n");
        exit(1);
    }

    int pipe_fd[2];
    if (pipe(pipe_fd) == -1) {
        perror("Pipe creation failed");
        exit(1);
    }

    pid_t child_pid = fork();

    if (child_pid == -1) {
        perror("Fork failed");
        exit(1);
    } else if (child_pid == 0) {
        
        generateFibonacci(n, pipe_fd);
    } else {
        
        wait(NULL); 

        close(pipe_fd[1]); 

        printf("Fibonacci sequence generated by the child process:\n");

        int fib_number;
        while (read(pipe_fd[0], &fib_number, sizeof(int)) > 0) {
            printf("%d ", fib_number);
        }

        printf("\n");

        close(pipe_fd[0]); 
    }

    return 0;
}

